### ISSUE TITLE
Cross-testing1

### ISSUE THREAD

**Issue by giji48** [harlach/JJC#3]
game was very good! Just a few small features that would make the game better/easier to use and a few bugs to fix. Overall the features work, there are no major bugs, and the game play is smooth. Was able to kill all enemies and enjoyed playing it. Well done!
This is also in a wiki page just in case.

**Comment by giji48** [comment]
Un-Invert Level -re-position camera

**Comment by giji48** [comment]
Outside of scope- keeps falling forever- try fixing bug with flag

**Comment by giji48** [comment]
Invisible wall- can go through

**Comment by giji48** [comment]
'Objectives' typo- from Objectives 2nd house

**Comment by giji48** [comment]
Name game

**Comment by giji48** [comment]
Re-add loading bar

**Comment by giji48** [comment]
Sound effects-moving/attacking

**Comment by giji48** [comment]
remove testing toolbar

**Comment by giji48** [comment]
Add 'dead' page- when player dies have a page that says "you are dead" and have buttons that directs them to start over or to leave

**Comment by giji48** [comment]
Save game option

**Comment by giji48** [comment]
Pause game option

**Comment by harlach** [comment]
hello
